export const dummyQuestions = [
  {
    question: "What is the capital of India?",
    option_1: "Colombo",
    option_2: "Jakarta",
    option_3: "New Delhi",
    option_4: "Anikat",
    correctAnswerIndex: 3, // Assuming option indexing starts at 1
  },
  {
    question: "Which planet is known as the Red Planet?",
    option_1: "Earth",
    option_2: "Mars",
    option_3: "Jupiter",
    option_4: "Saturn",
    correctAnswerIndex: 2,
  },
  {
    question: "What is the largest ocean on Earth?",
    option_1: "Atlantic Ocean",
    option_2: "Indian Ocean",
    option_3: "Arctic Ocean",
    option_4: "Pacific Ocean",
    correctAnswerIndex: 4,
  },
  {
    question: "In which year did the Titanic sink?",
    option_1: "1912",
    option_2: "1915",
    option_3: "1918",
    option_4: "1923",
    correctAnswerIndex: 1,
  },
  {
    question: "Who wrote 'Hamlet'?",
    option_1: "Leo Tolstoy",
    option_2: "William Shakespeare",
    option_3: "Mark Twain",
    option_4: "Charles Dickens",
    correctAnswerIndex: 2,
  },
  {
    question: "Which is the smallest country in the world?",
    option_1: "Monaco",
    option_2: "Nauru",
    option_3: "Vatican City",
    option_4: "Liechtenstein",
    correctAnswerIndex: 3,
  },
  {
    question: "What is the chemical symbol for gold?",
    option_1: "Au",
    option_2: "Ag",
    option_3: "Ga",
    option_4: "Ge",
    correctAnswerIndex: 1,
  },
  {
    question: "Who is known as the Father of Computers?",
    option_1: "Charles Babbage",
    option_2: "Alan Turing",
    option_3: "John von Neumann",
    option_4: "Blaise Pascal",
    correctAnswerIndex: 1,
  },
  {
    question: "Which human organ is capable of regenerating tissue?",
    option_1: "Heart",
    option_2: "Liver",
    option_3: "Lung",
    option_4: "Kidney",
    correctAnswerIndex: 2,
  },
  {
    question: "What year did the first human land on the moon?",
    option_1: "1969",
    option_2: "1972",
    option_3: "1965",
    option_4: "1970",
    correctAnswerIndex: 1,
  },
  {
    question: "What is the highest-grossing film of all time?",
    option_1: "Titanic",
    option_2: "Avatar",
    option_3: "Avengers: Endgame",
    option_4: "Star Wars: The Force Awakens",
    correctAnswerIndex: 3, // This might need updating based on current data.
  },
  {
    question: "What is the most abundant gas in the Earth's atmosphere?",
    option_1: "Oxygen",
    option_2: "Hydrogen",
    option_3: "Carbon Dioxide",
    option_4: "Nitrogen",
    correctAnswerIndex: 4,
  },
  {
    question: "Who painted the Mona Lisa?",
    option_1: "Vincent Van Gogh",
    option_2: "Leonardo da Vinci",
    option_3: "Pablo Picasso",
    option_4: "Claude Monet",
    correctAnswerIndex: 2,
  },
  {
    question: "What is the longest river in the world?",
    option_1: "Amazon River",
    option_2: "Nile River",
    option_3: "Yangtze River",
    option_4: "Mississippi River",
    correctAnswerIndex: 2,
  },
  {
    question: "Which animal is known as the King of the Jungle?",
    option_1: "Tiger",
    option_2: "Lion",
    option_3: "Elephant",
    option_4: "Gorilla",
    correctAnswerIndex: 2,
  },
];
